// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSW.Model.MyDbContext;

namespace PSW.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220903152039_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("PSW.Model.Users.RegUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RegUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RegUser");
                });

            modelBuilder.Entity("PSW.Model.Users.Admin", b =>
                {
                    b.HasBaseType("PSW.Model.Users.RegUser");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("PSW.Model.Users.Doctor", b =>
                {
                    b.HasBaseType("PSW.Model.Users.RegUser");

                    b.Property<int>("DoctorType")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Doctor");
                });

            modelBuilder.Entity("PSW.Model.Users.Patient", b =>
                {
                    b.HasBaseType("PSW.Model.Users.RegUser");

                    b.Property<string>("BloodType")
                        .HasColumnType("longtext");

                    b.Property<string>("HealthCard")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsBlockable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
